#!/command/with-contenv bash

echo "Starting named pipe log stream..."
mkdir -p $(dirname $PIPE_PATH)
[ -e "$PIPE_PATH" ] || (echo "No PIPE_PATH present, creating..." && mkfifo $PIPE_PATH)

# Keep pipe open to be non-blocking
exec 3<>$PIPE_PATH &
# https://unix.stackexchange.com/questions/496810/using-exec-3-to-keep-a-named-pipe-open
#
## Testing pt. 1
# exec cat $PIPE_PATH > /var/log/rsyslog/rsyslog.log
##
## Testing pt. 2
## Stream to a unique pipeto.me URL, and curl -T. the 
## pipeto.me URL in another terminal to see the stream output.
# exec cat $PIPE_PATH |\
#     curl -s -T- https://pipeto.me/MtKXZUWH
##
## Testing pt. 3
## Need to push to a device to test this
exec cat $PIPE_PATH |\
    zstd --format=gzip |\
    curl --data-binary @- \
    -X POST \
    -H "Authorization: Bearer $BALENA_API_KEY" \
    -H "Content-Type: application/x-ndjson" \
    -H "Content-Encoding: gzip" \
    "$BALENA_API_URL/device/v2/$BALENA_DEVICE_UUID/log-stream"
##