version: '2.1'

services:
  rsyslog:
    build: .
    restart: unless_stopped
    volumes:
      - work:/var/spool/rsyslog
      - state:/var/run/rsyslog # For journal.state file
      # - logs:/var/log/rsyslog # For testing with omfile or piping to file
    environment:
      - PIPE_PATH=/etc/pipe/stream_pipe
      - MAX_MESSAGE_LENGTH=10000
    labels:
      io.balena.features.journal-logs: '1'
      io.balena.features.balena-api: '1'
  logger: # Test logger for sanity checking balena log streaming
    build: ./logger
    restart: unless_stopped

volumes:
  work:
  state:
  logs:
  pipe:
