#!/command/with-contenv bash

# Added to prevent pipe from starting if not using ompipe
[ "$PIPE_PATH" == "" ] && sleep infinity

mkdir -p $(dirname $PIPE_PATH)
[ -e "$PIPE_PATH" ] || (echo "No PIPE_PATH present, creating..." && mkfifo $PIPE_PATH)

# Keep pipe open to be non-blocking
# https://unix.stackexchange.com/questions/496810/using-exec-3-to-keep-a-named-pipe-open
exec 3<>$PIPE_PATH

echo "Starting named pipe log stream..."

## Testing pt. 1
# exec cat $PIPE_PATH > /var/log/rsyslog/rsyslog.log
##
## Testing pt. 2
## Stream to a unique pipeto.me URL, and curl -T. the 
## pipeto.me URL in another terminal to see the stream output.
exec cat $PIPE_PATH >
    curl -s -T- https://pipeto.me/MtKXZUWH
##
## Testing pt. 3
## zstd functionality
# exec cat $PIPE_PATH |\
#     zstd -vvv --format=gzip |\
#     zstd -vvv -d -o /var/log/rsyslog/rsyslog.log
## Testing pt. 4
## Need to push to a device to test this
# exec cat $PIPE_PATH |\
#     zstd --format=gzip |\
#     curl --data-binary @- \
#     -X POST \
#     -H "Authorization: Bearer $BALENA_API_KEY" \
#     -H "Content-Type: application/x-ndjson" \
#     -H "Content-Encoding: gzip" \
#     "$BALENA_API_URL/device/v2/$BALENA_DEVICE_UUID/log-stream"
##